# Generated by Django 2.1.2 on 2018-10-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('run', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField(blank=True)),
                ('telefono', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('comunaDomicilio', models.CharField(max_length=50)),
                ('comunaTrabajo', models.CharField(max_length=50)),
            ],
        ),
    ]
