# Generated by Django 2.1.2 on 2018-10-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
