# Generated by Django 2.1.2 on 2018-10-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='run',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
