# Generated by Django 2.1.2 on 2018-10-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('capacidad', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
            ],
        ),
    ]
